export const GET_ALL_COVID_DATA = 'GET_ALL_COVID_DATA';
export const GET_ALL_COVID_DATA_SUCCESS = 'GET_ALL_COVID_DATA_SUCCESS';
export const GET_ALL_COVID_DATA_FAILED = 'GET_ALL_COVID_DATA_FAILED';

export const GET_STATES_BY_COUNTRY = 'GET_STATES_BY_COUNTRY';
export const GET_STATES_BY_COUNTRY_FAILED = 'GET_STATES_BY_COUNTRY_FAILED';
